const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const K='zenf_demo_v3';
const seed={guests:[{id:1,name:'Carlos Mendes',phone:'(47) 99911-2233',doc:'***.***.***-**',note:'Prefere quarto silencioso'},{id:2,name:'Mariana Souza',phone:'(41) 99822-1040',doc:'',note:''}],rooms:[{id:101,type:'Standard Individual',price:140,status:'Ocupado'},{id:102,type:'Standard Duplo',price:320,status:'Disponível'},{id:203,type:'Luxo Individual',price:220,status:'Ocupado'},{id:204,type:'Luxo Duplo',price:320,status:'Disponível'},{id:301,type:'Standard Triplo',price:420,status:'Disponível'}],reservations:[{id:1,guestId:1,roomId:203,in:'2026-08-27',out:'2026-08-29',value:440,status:'Hospedado',paid:220,vehicle:{model:'Chevrolet Onix',color:'Branco',plate:'ABC1D23'}},{id:2,guestId:2,roomId:101,in:'2026-08-27',out:'2026-08-28',value:140,status:'Hospedado',paid:140,vehicle:null}]};
let db=JSON.parse(localStorage.getItem(K)||'null')||structuredClone(seed); const save=()=>localStorage.setItem(K,JSON.stringify(db));
const fmt=d=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR'):'—'; const money=v=>(Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function guest(id){return db.guests.find(x=>x.id==id)} function room(id){return db.rooms.find(x=>x.id==id)}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function setView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('aside nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#title').textContent={dashboard:'Visão geral',reservas:'Reservas',hospedes:'Hóspedes',quartos:'Quartos',estacionamento:'Estacionamento',financeiro:'Financeiro'}[id];$('#newBtn').style.display=id==='reservas'||id==='dashboard'?'block':'none';$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show');render()}
$$('aside nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));$('#sideBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#scrim').classList.add('show')};$('#scrim').onclick=()=>{$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show')};
function openModal(id){$('#'+id).classList.add('show');$('#'+id).setAttribute('aria-hidden','false')} function closeModal(id){$('#'+id).classList.remove('show');$('#'+id).setAttribute('aria-hidden','true')} $$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));
function populate(){const go=$('#reservationGuest'),ro=$('#reservationRoom'),vr=$('#vehicleReservation');go.innerHTML='<option value="">Selecione...</option>'+db.guests.map(g=>`<option value="${g.id}">${g.name}</option>`).join('');ro.innerHTML='<option value="">Selecione...</option>'+db.rooms.map(r=>`<option value="${r.id}">Quarto ${r.id} — ${r.type}</option>`).join('');vr.innerHTML='<option value="">Selecione...</option>'+db.reservations.filter(r=>r.status!=='Finalizada'&&r.status!=='Cancelada').map(r=>`<option value="${r.id}">Quarto ${r.roomId} — ${guest(r.guestId)?.name||''}</option>`).join('')}
function render(){populate();const active=db.reservations.filter(r=>r.status==='Hospedado');const confirmed=db.reservations.filter(r=>r.status==='Confirmada');const totalRooms=db.rooms.length, occupied=new Set(active.map(r=>r.roomId)).size;$('#dashboardStats').innerHTML=[['Quartos ocupados',`${occupied}/${totalRooms}`],['Reservas ativas',active.length+confirmed.length],['Hóspedes cadastrados',db.guests.length],['Veículos no pátio',active.filter(r=>r.vehicle).length]].map(([a,b])=>`<div class="stat"><small>${a}</small><strong>${b}</strong></div>`).join('');$('#todayLabel').textContent=new Date().toLocaleDateString('pt-BR');$('#todayTimeline').innerHTML=(active.length?active.map(r=>`<div class="timeline-item"><div><strong>${guest(r.guestId)?.name}</strong><span>Quarto ${r.roomId} • saída ${fmt(r.out)}</span></div><span class="badge ok">Hospedado</span></div>`):'<div class="meta">Sem movimentações.</div>').join('');$('#parkingMini').innerHTML=active.filter(r=>r.vehicle).map(r=>`<div class="mini-item"><div><strong>${r.vehicle.plate}</strong><span>${r.vehicle.model} • Quarto ${r.roomId}</span></div></div>`).join('')||'<div class="meta">Nenhum veículo registrado.</div>';
$('#reservationsTable').innerHTML=db.reservations.map(r=>`<tr><td><strong>${guest(r.guestId)?.name||'—'}</strong></td><td>${r.roomId}</td><td>${fmt(r.in)}</td><td>${fmt(r.out)}</td><td>${r.vehicle?r.vehicle.plate:'—'}</td><td><span class="badge ${r.status==='Hospedado'?'ok':r.status==='Confirmada'?'warn':''}">${r.status}</span></td><td><button class="link-btn" onclick="finishRes(${r.id})">Finalizar</button></td></tr>`).join('');
$('#guestCards').innerHTML=db.guests.map(g=>`<div class="card"><h3>${g.name}</h3><div class="meta">${g.phone}<br>${g.doc||'Documento não informado'}${g.note?'<br>'+g.note:''}</div></div>`).join('');$('#roomCards').innerHTML=db.rooms.map(r=>`<div class="room-card"><div class="room-no">${r.id}</div><h3>${r.type}</h3><div class="meta">Diária ${money(r.price)}</div><footer><span class="badge ${r.status==='Disponível'?'ok':'warn'}">${r.status}</span></footer></div>`).join('');
$('#parkingCards').innerHTML=db.reservations.filter(r=>r.vehicle&&r.status!=='Finalizada'&&r.status!=='Cancelada').map(r=>`<div class="parking-card"><div class="plate">${r.vehicle.plate}</div><h3>${r.vehicle.model} • ${r.vehicle.color}</h3><div class="meta">${guest(r.guestId)?.name}<br>Quarto ${r.roomId}<br>Saída prevista ${fmt(r.out)}</div></div>`).join('')||'<div class="meta">Nenhum veículo no estacionamento.</div>';const predicted=db.reservations.filter(r=>r.status!=='Cancelada').reduce((s,r)=>s+(Number(r.value)||0),0),received=db.reservations.reduce((s,r)=>s+(Number(r.paid)||0),0);$('#financeStats').innerHTML=[['Total previsto',money(predicted)],['Recebido',money(received)],['Pendente',money(predicted-received)],['Reservas',db.reservations.length]].map(([a,b])=>`<div class="stat"><small>${a}</small><strong>${b}</strong></div>`).join('')}
window.finishRes=id=>{const r=db.reservations.find(x=>x.id===id);if(!r)return;r.status='Finalizada';const rm=room(r.roomId);if(rm)rm.status='Disponível';save();render();toast('Hospedagem finalizada')};
$('#newBtn').onclick=$('#addReservation').onclick=()=>openModal('reservationModal');$('#addGuest').onclick=()=>openModal('guestModal');$('#addVehicle').onclick=()=>openModal('vehicleModal');$('#hasVehicle').onchange=e=>$('#vehicleFields').classList.toggle('show',e.target.checked);
$('#guestForm').onsubmit=e=>{e.preventDefault();db.guests.push({id:Date.now(),name:$('#guestName').value.trim(),phone:$('#guestPhone').value.trim(),doc:$('#guestDocument').value.trim(),note:$('#guestNote').value.trim()});save();e.target.reset();closeModal('guestModal');render();toast('Hóspede cadastrado')};
$('#reservationForm').onsubmit=e=>{e.preventDefault();const rid=Number($('#reservationRoom').value),veh=$('#hasVehicle').checked?{model:$('#vehicleModel').value.trim(),color:$('#vehicleColor').value.trim(),plate:$('#vehiclePlate').value.trim().toUpperCase()}:null;db.reservations.push({id:Date.now(),guestId:Number($('#reservationGuest').value),roomId:rid,in:$('#checkIn').value,out:$('#checkOut').value,value:Number($('#reservationValue').value)||0,status:$('#reservationStatus').value,paid:0,vehicle:veh});const rm=room(rid);if(rm&&$('#reservationStatus').value==='Hospedado')rm.status='Ocupado';save();e.target.reset();$('#vehicleFields').classList.remove('show');closeModal('reservationModal');render();toast('Reserva salva')};
$('#vehicleForm').onsubmit=e=>{e.preventDefault();const r=db.reservations.find(x=>x.id==$('#vehicleReservation').value);if(r)r.vehicle={model:$('#standaloneVehicleModel').value.trim(),color:$('#standaloneVehicleColor').value.trim(),plate:$('#standaloneVehiclePlate').value.trim().toUpperCase()};save();e.target.reset();closeModal('vehicleModal');render();toast('Veículo vinculado ao quarto')};
render();
